### ISSUE TITLE
Missing $crate:: prefix in scope!

### ISSUE THREAD

**Issue by MaulingMonkey** [jonasmr/microprofile-rust#2]
https://github.com/jonasmr/microprofile-rust/blob/2746d44bbc40cbb32b9739e381590c21af025ebe/src/lib.rs#L204-L206

This prevents using `microprofile::scope!("group", "name")`

**Comment by Wumpf** [comment]
@jonasmr Fixed now, plz close :)
(and thx for merging the PR!)
